spring:
  application:
    name: app-consumer

server:
  port: 8001

eureka:
  client:
    service-url:
         defaultZone: http://localhost:8100/eureka/ #注册中心地址
    register-with-eureka: true
    fetch-registry: true

  instance:
    #Eureka服务端在收到最后一次心跳之后等待的时间上限，单位为秒，超过则剔除（客户端告诉服务端按照此规则等待自己）
    lease-expiration-duration-in-seconds: 2
    ##Eureka客户端向服务端发送心跳的时间间隔，单位为秒（客户端告诉服务端自己会按照该规则）
    lease-renewal-interval-in-seconds: 1


